### ISSUE TITLE
Trace results should be shown one at a time

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#40]
When more than one trace is executed concurrently, the results, whether a graphic(with aggegrate) or selection, for each result will only be shown one at a time.

**Comment by previnWong** [comment]
addressed in latest commit, please pull and verify.

**Comment by avezina** [comment]
we should probably still have a radio button to determine which one is displayed on the map (active selection), rather than switch selection on expand/collapse state change
![image](https://user-images.githubusercontent.com/50338557/126825622-6eb356bd-a5ad-47e6-97fc-3b3b4a04721c.png)

**Comment by avezina** [comment]
Looks good, implemented with highlight option for each trace, and highlight on drill in
![image](https://user-images.githubusercontent.com/50338557/127403788-afe0750f-4c1a-40f1-919c-11fc245be300.png)
